name: ad110mqtt
version: 2023.4.18
slug: ad110mqtt-addon
description: A Home Assistant addon for ad110 doorbell
url: https://github.com/snozzley/ad110mqtt-addon/blob/master/README.md
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
image: snozzley/ad110mqtt-addon-{arch}
codenotary: cas@mathesonsteplock.ca
startup: services
boot: auto
init: false
map:
- ssl:ro
services:
- mqtt:need
options:
  amcrest_host: ''
  amcrest_port: 80
  amcrest_username: admin
  amcrest_password: ''
  storage_poll_interval: 3600
  device_name: ''
  home_assistant: true
  home_assistant_prefix: ''
schema:
  amcrest_host: str
  amcrest_port: int
  amcrest_username: str
  amcrest_password: str
  storage_poll_interval: int
  device_name: str
  home_assistant: bool
  home_assistant_prefix: str
